substitutions:
  _VERSION: 0.0.0
steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['pack']
  - name: 'python:3-alpine'
    id: 'package'
    args: ['python', 'setup.py', 'sdist']
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'copy-tagged-version'
    args:
      [
        'cp',
        'dist/jupyterlab_gcsfilebrowser*.tar.gz',
        'gs://deeplearning-platform-ui-public/jupyterlab_gcsfilebrowser-$_VERSION.tar.gz',
      ]
    waitFor: ['package']
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'copy-latest'
    args:
      [
        'cp',
        'dist/jupyterlab_gcsfilebrowser*.tar.gz',
        'gs://deeplearning-platform-ui-public/jupyterlab_gcsfilebrowser-latest.tar.gz',
      ]
    waitFor: ['package']
tags: ['release']
