# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import datetime
import subprocess
import sys
import typing


from abc import abstractmethod
from traitlets import Int, Unicode
from jupyter_server.gateway.gateway_client import GatewayTokenRenewerBase


class CachedTokenRenewerBase(GatewayTokenRenewerBase):
    """Token renewer base class that only renews the token after a specified timeout."""

    token_lifetime_seconds = Int(
        default_value=300,
        config=True,
        help="""Time (in seconds) to wait between successive token renewals.""",
    )

    @abstractmethod
    def force_new_token(
        self,
        auth_header_key: str,
        auth_scheme: typing.Union[str, None],
        **kwargs: typing.Any,
    ):
        pass

    _created = datetime.datetime.min

    def get_token(
        self,
        auth_header_key: str,
        auth_scheme: typing.Union[str, None],
        auth_token: str,
        **kwargs: typing.Any,
    ):
        current_time = datetime.datetime.now()
        duration = (current_time - self._created).total_seconds()
        if (not auth_token) or (duration > self.token_lifetime_seconds):
            auth_token = self.force_new_token(auth_header_key, auth_scheme, **kwargs)
            self._created = datetime.datetime.now()

        return auth_token


class CommandTokenRenewer(CachedTokenRenewerBase):
    """Token renewer that invokes an external command to generate the token.

    The token command is run ahead of time, in the background, so that its
    result is already available by the time it is needed. That keeps
    `force_new_token` from blocking the Jupyter server's event loop while
    waiting for the (potentially slow) command to complete.
    """

    token_command = Unicode(
        default_value="",
        config=True,
        help="""External command run to generate auth tokens.""",
    )

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        # Start generating the first token immediately so that the command can
        # run in parallel with the rest of the server's startup.
        self._pending_process = (
            self._start_token_command() if self.token_command else None
        )

    def _start_token_command(self):
        """Start running the token command in a background subprocess.

        We reuse the system stderr for the command so that any prompts from it
        will be displayed to the user.
        """
        return subprocess.Popen(
            self.token_command,
            stdin=subprocess.DEVNULL,
            stderr=sys.stderr,
            stdout=subprocess.PIPE,
            shell=True,
            encoding="UTF-8",
        )

    def force_new_token(
        self,
        auth_header_key: str,
        auth_scheme: typing.Union[str, None],
        **kwargs: typing.Any,
    ):
        """Return the token generated by the most recently started command."""
        p = self._pending_process or self._start_token_command()

        # The command was started the last time a token was generated, so it
        # has almost certainly already completed and this will not block.
        stdout, _ = p.communicate()

        # Start generating the next token now so that it, too, is ready before
        # we are asked for it.
        self._pending_process = self._start_token_command()

        if p.returncode != 0:
            raise subprocess.CalledProcessError(
                p.returncode, self.token_command, output=stdout
            )
        return stdout.strip()
