name: Presubmit
on:
  pull_request:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "10"
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install Pipenv
        run: pip install pipenv && pipenv install -d
      - name: Build TypeScript
        run: npm ci &&
          npm run bootstrap &&
          npm run build
      - name: Build JupyterLab
        run: source $(pipenv --venv)/bin/activate &&
          scripts/build_jupyterlab.sh
      - name: Build Python
        run: source $(pipenv --venv)/bin/activate &&
          scripts/build_python_packages.sh
      - name: Run Tests
        run: source $(pipenv --venv)/bin/activate &&
          scripts/run_all_tests.sh
  test_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses:  actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Instapp pytest
        run: |
          python -m pip install pytest
      - name: Instapp traitlets
        run: |
          python -m pip install traitlets
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Test gcloud config
        run: |
          pytest jupyterlab_gcloud
