name: Presubmit
on:
  pull_request:
    branches:
      - "*"
jobs:
  test_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses:  actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install pytest
        run: |
          python -m pip install pytest
      - name: Install dependencies
        run: |
          python -m pip install jupyter_server traitlets pytest-jupyter
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: Install google-cloud-jupyter-config
        run: |
          python -m pip install ./google-cloud-jupyter-config
      - name: Test gcloud config
        run: |
          pytest ./google-cloud-jupyter-config
      - name: Install kernels-mixer
        run: |
          python -m pip install ./kernels-mixer
      - name: Test kernels-mixer
        run: |
          pytest ./kernels-mixer
